package pa.cifpaviles.dam.aeropuerto.componentes;

import java.awt.Window;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import pa.cifpaviles.dam.aeropuerto.dto.Companya;
import pa.cifpaviles.dam.aeropuerto.logica.LogicaNegocio;
import pa.cifpaviles.dam.aeropuerto.dto.Municipio;
import pa.cifpaviles.dam.aeropuerto.gui.FrmCompanyas;

public class EditarCompanya extends javax.swing.JPanel {

    private Companya companya;
    private FrmCompanyas frmCompanyas;

    public Companya getCompanya() {
        return companya;
    }

    private boolean habilitado;

    public boolean isHabilitado() {
        return habilitado;
    }

    public void setHabilitado(boolean habilitado) {
        this.habilitado = habilitado;
    }

    public void setCompanya(Companya comp) {
        this.companya = comp;
        if (!companya.getCodigo().isBlank()) {
            txtCodigo.setText(comp.getCodigo());
            txtNombre.setText(comp.getNombre());
            txtDireccion.setText(comp.getDireccion());
            txtTlfInfoAeropuerto.setText(comp.getTelefonoInformacion());
            txtTlfInfoPasajero.setText(comp.getTelefonoPasajeros());
        }
    }

    /**
     * private int prefijo; private String codigo; private String nombre;
     * private String direccion; private String municipio; private String
     * telefonoPasajeros; private String telefonoInformacion; Creates new form
     * DatosCompanya
     */
    public EditarCompanya(FrmCompanyas frmCompanyas, Companya companya) {
        initComponents();
        fillMunicipios();
        this.frmCompanyas = frmCompanyas;
        this.companya = companya; // Asignar la compañía proporcionada al atributo companya
        if (companya != null && !companya.getCodigo().isBlank()) {
            txtPrefijo.setText(String.valueOf(companya.getPrefijo()));
            txtCodigo.setText(companya.getCodigo());
            txtNombre.setText(companya.getNombre());
            txtDireccion.setText(companya.getDireccion());
            txtTlfInfoAeropuerto.setText(companya.getTelefonoInformacion());
            txtTlfInfoPasajero.setText(companya.getTelefonoPasajeros());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodigo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lbldDireccion = new javax.swing.JLabel();
        lblMunicipio = new javax.swing.JLabel();
        lblTlfInfoPasajero = new javax.swing.JLabel();
        lblTlfInfoAeropuerto = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtTlfInfoPasajero = new javax.swing.JTextField();
        txtTlfInfoAeropuerto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDireccion = new javax.swing.JTextArea();
        cbMunicipios = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPrefijo = new javax.swing.JTextField();

        lblCodigo.setText("Código:");

        lblNombre.setText("Nombre:");

        lbldDireccion.setText("Dirección:");

        lblMunicipio.setText("Municipio:");

        lblTlfInfoPasajero.setText("Teléfono de información al pasajero:");

        lblTlfInfoAeropuerto.setText("Teléfono de información al aeropuerto:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtDireccion.setColumns(20);
        txtDireccion.setRows(5);
        jScrollPane1.setViewportView(txtDireccion);

        cbMunicipios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMunicipiosActionPerformed(evt);
            }
        });

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel1.setText("Prefijo:");

        txtPrefijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrefijoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMunicipio)
                    .addComponent(lbldDireccion)
                    .addComponent(lblNombre)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTlfInfoAeropuerto)
                        .addComponent(lblTlfInfoPasajero, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblCodigo, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel1))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtPrefijo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTlfInfoAeropuerto, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTlfInfoPasajero, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cbMunicipios, javax.swing.GroupLayout.Alignment.LEADING, 0, 146, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 281, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtPrefijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldDireccion, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMunicipio)
                    .addComponent(cbMunicipios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTlfInfoPasajero)
                    .addComponent(txtTlfInfoPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTlfInfoAeropuerto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTlfInfoAeropuerto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbMunicipiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMunicipiosActionPerformed

    }//GEN-LAST:event_cbMunicipiosActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarCompanya();
        cerrarComponente();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtPrefijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrefijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrefijoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<Municipio> cbMunicipios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblMunicipio;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTlfInfoAeropuerto;
    private javax.swing.JLabel lblTlfInfoPasajero;
    private javax.swing.JLabel lbldDireccion;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrefijo;
    private javax.swing.JTextField txtTlfInfoAeropuerto;
    private javax.swing.JTextField txtTlfInfoPasajero;
    // End of variables declaration//GEN-END:variables

    private void fillMunicipios() {
        LogicaNegocio.getAllMunicipios().forEach(m -> cbMunicipios.addItem(m));
    }

    private void guardarCompanya() {
        try {
            int prefijo = Integer.parseInt(txtPrefijo.getText());
            String codigo = txtCodigo.getText();
            String nombre = txtNombre.getText();
            String direccion = txtDireccion.getText();
            Municipio municipioSeleccionado = (Municipio) cbMunicipios.getSelectedItem();
            String nombreMunicipio = municipioSeleccionado.nombre();
            String telefonoPasajeros = txtTlfInfoPasajero.getText();
            String telefonoInformacion = txtTlfInfoAeropuerto.getText();

            // Verificar si la compañía ya existe
            Companya companyaExistente = LogicaNegocio.getCompanyaByCodigo(codigo);

            if (companyaExistente != null) {
                // Actualizar la compañía existente
                companyaExistente.setPrefijo(prefijo);
                companyaExistente.setNombre(nombre);
                companyaExistente.setDireccion(direccion);
                companyaExistente.setMunicipio(nombreMunicipio);
                companyaExistente.setTelefonoPasajeros(telefonoPasajeros);
                companyaExistente.setTelefonoInformacion(telefonoInformacion);
                LogicaNegocio.updateCompanyaByCodigo(codigo, companya); // Asegúrate de que este método exista y funcione correctamente
            } else {
                // Crear y agregar una nueva compañía
                Companya nuevaCompanya = new Companya(prefijo, codigo, nombre, direccion, nombreMunicipio, telefonoPasajeros, telefonoInformacion);
                LogicaNegocio.addCompanya(nuevaCompanya);
            }

            frmCompanyas.loadCompanies(); // Actualizar la lista de compañías en la interfaz principal
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error en el formato del número: " + e.getMessage());
        }
    }

    private void cerrarComponente() {
        Window window = SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();
        }
    }

}
